/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/hand_asl2.gltf -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.SkinnedMesh
    sleeve: THREE.Mesh
    Bone: THREE.Bone
  }
  materials: {
    Skin: THREE.MeshStandardMaterial
    Sleeve: THREE.MeshStandardMaterial
  }
}

export function Model2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/hand_asl2.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} scale={1}>
      <mesh geometry={nodes.sleeve.geometry} material={materials.Sleeve} scale={0.73} />
      <group scale={0.7}>

        <primitive object={nodes.Bone} />
        <skinnedMesh geometry={nodes.Cube.geometry} material={materials.Skin} skeleton={nodes.Cube.skeleton} />

      </group>

    </group>
  )
}

useGLTF.preload('/hand_asl2.gltf')
