/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 hand_asl.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hand_asl.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sleeve.geometry} material={materials.Sleeve} />
      <primitive object={nodes.Bone} />
      <skinnedMesh geometry={nodes.Cube.geometry} material={materials.Skin} skeleton={nodes.Cube.skeleton} />
    </group>
  )
}

useGLTF.preload('/hand_asl.glb')
